import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy | Ruta Colombia',
  description: 'Privacy Policy for Ruta Colombia. Learn how we collect, use, and protect your personal information.',
};

export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
      <h1 className="font-serif text-4xl font-bold text-gray-900 mb-4">Privacy Policy</h1>
      <div className="w-16 h-1 bg-teal-500 mb-8 rounded-full" />
      <div className="prose max-w-none text-gray-700 space-y-6">
        <p className="text-sm text-gray-600">Last updated: April 2026</p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">1. Who We Are</h2>
        <p>
          Ruta Colombia is a travel and lifestyle guide for Colombia, operated by <strong>Maia Management Group S.A.S.</strong>, a company registered in Colombia. We are committed to protecting your privacy and ensuring you have a positive experience on our website.
        </p>
        <p>
          Website: https://ruta-colombia.com
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">2. Information We Collect</h2>
        <p>
          We collect information in the following ways:
        </p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li><strong>Contact Forms:</strong> When you submit a contact form, we collect the information you provide (name, email, message). This data is processed through Netlify Forms.</li>
          <li><strong>Analytics Data:</strong> We use Google Analytics to understand how visitors use our website. This includes information about your device, browser, pages visited, and time spent on our site.</li>
          <li><strong>Advertising Data:</strong> We use Google AdSense to display personalized advertisements. Google may collect information about your browsing behavior to serve relevant ads.</li>
          <li><strong>Cookies:</strong> Our website uses cookies to enhance your experience and track site usage (see section on cookies below).</li>
        </ul>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">3. Google Analytics and Cookies</h2>
        <p>
          Google Analytics is a web analytics service provided by Google, Inc. It uses cookies to help us analyze how you use the website. The information generated by the cookie about your use of the website (including your IP address, which may be transmitted to Google's servers in the United States) is used to evaluate your use of the website, compile reports on website activity, and provide other services related to website activity and internet usage.
        </p>
        <p>
          Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">4. Google AdSense</h2>
        <p>
          We use Google AdSense to display advertisements on our website. Google AdSense uses cookies and other technologies to serve ads based on your prior visits to our website and other websites. You can opt out of personalized advertising through Google's <a href="https://myadcenter.google.com" className="text-teal-500 hover:text-teal-600">Ad Settings</a>.
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">5. How We Use Your Information</h2>
        <p>
          We use the information we collect for the following purposes:
        </p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li>To respond to your inquiries and provide customer support</li>
          <li>To analyze website usage and improve our services</li>
          <li>To deliver relevant content and personalized advertisements</li>
          <li>To comply with legal obligations</li>
        </ul>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">6. Third-Party Services</h2>
        <p>
          Our website uses the following third-party services, which may collect and process your data:
        </p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li><strong>Google Analytics:</strong> For website analytics and performance tracking</li>
          <li><strong>Google AdSense:</strong> For displaying personalized advertisements</li>
          <li><strong>Netlify Forms:</strong> For processing contact form submissions</li>
        </ul>
        <p>
          These third parties have their own privacy policies and are responsible for their handling of your data. We recommend reviewing their privacy policies for more information.
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">7. Data Retention</h2>
        <p>
          We retain information collected through contact forms for as long as necessary to respond to your inquiry or as required by law. Analytics data is typically retained by Google for up to 26 months. You may request deletion of your personal information at any time by contacting us (see contact information below).
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">8. Your Rights</h2>
        <p>
          Depending on your location, you may have the following rights regarding your personal information:
        </p>
        <ul className="list-disc list-inside space-y-2 ml-4">
          <li><strong>Right to Access:</strong> You can request access to the personal information we hold about you</li>
          <li><strong>Right to Correction:</strong> You can request correction of inaccurate or incomplete information</li>
          <li><strong>Right to Deletion:</strong> You can request deletion of your personal information, subject to legal obligations</li>
          <li><strong>Right to Restrict Processing:</strong> You can request restriction of how we process your data</li>
          <li><strong>Right to Portability:</strong> You can request a copy of your data in a portable format</li>
        </ul>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">9. Security</h2>
        <p>
          We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet or electronic storage is completely secure. We cannot guarantee absolute security.
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">10. Contact Information</h2>
        <p>
          If you have questions about this Privacy Policy, or if you wish to exercise any of your rights, please contact us at:
        </p>
        <p>
          <strong>Maia Management Group S.A.S.</strong><br />
          Colombia<br />
          Email: info@ruta-colombia.com
        </p>

        <h2 className="font-serif text-2xl font-bold text-gray-900 mt-8 mb-4">11. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify you of any significant changes by updating the "Last updated" date at the top of this page. Your continued use of our website following the posting of changes means you accept those changes.
        </p>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <p className="text-sm text-gray-600">
            Return to <Link href="/" className="text-teal-500 hover:text-teal-600">home</Link> or view our <Link href="/terms/" className="text-teal-500 hover:text-teal-600">terms of service</Link>.
          </p>
        </div>
      </div>
    </div>
  );
}
